name: CI

on:
  push:

jobs:
  treefmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop --command bash -c "treefmt --fail-on-change"

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
